title: Welcome to Yuxuan Liang's Homepage
url: 'http://yuxuanliang.com'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
# style: styles-2
# style: styles-3
# style: styles-4
# style: styles-5 
style: styles-6


#Profile information
name: Yuxuan Liang
tagline: AI Explorer
pic:   #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: yuxliang@outlook.com
# phone: 
website:  #do not add http://
linkedin: yoshall
# github:
# twitter: 

# Tracker
analytics: UA-117975635-1
#Update all the sections by editing the files inside _includes folder.
