
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://yuxuanliang"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: 

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Yuxuan Liang "
title: "Yuxuan Liang"
description: "Blog and website of Yuxuan Liang , blogging mainly for tech. Opinions expressed are mine."
keywords: "Yuxuan, Liang, personal, jekyll, theme"
favicon: "/img/boy.ico"

################
# Header layout #
################

black-favicon: "/img/the-avengers.ico"

background-img: "../img/misty-forest.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "From small beginnings comes great things."
  - text: "It is never too late to learn."
  - text: "Nothing down, nothing up."
  - text: "A bosom friend afar brings a distant land near."
  - text: "能享受最好的，能承受最坏的。"


me-img: "/img/me.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "Castleliang"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/ms.png"
    date: "December 2015 - Today"
    description: "<b>Microsoft research asia</b> <br/>Research intern <br/>in Urban Computing Group"
  - image: "/img/timeline/xidian.png"
    date: "September 2012 - June 2016"
    description: "<b>Xidian University</b><br/>Undergraduate student<br/>major in <b>Computer Science</b>"
  - image: "/img/timeline/changjun.png"
    date: "September 2009 - June 2012"
    description: "<b>Changjun High School</b><br/>Senior high student<br/>in experimental class"

# First image of the Timeline

timeline-img: "/img/me.png"

###########
# Contact #
###########

email: ""


################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Yuxuan Liang lives in Beijing, China, where he works as a research intern in Microsoft Research Asia"
author_blurb_image: "/img/shulan.gif"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/"
  - title: "github"
    url: "https://github.com/"
  - title: "weibo"
    url: "http://weibo.com/"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
